version: 2

project_name: breakfastLoveBot

before:
  hooks:
    - go mod tidy

builds:
  - id: breakfastLoveBot
    main: ./cmd/breakfastLoveBot
    binary: breakfastLoveBot
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - breakfastLoveBot
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
